-- MySQL Script generated by MySQL Workbench
-- Wed Sep 28 15:31:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Villages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Villages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `players_id` INT NOT NULL,
  PRIMARY KEY (`id`, `players_id`),
  CONSTRAINT `fk_Villages_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `mydb`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`troops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`troops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `damage` VARCHAR(45) NULL,
  `distance_damage` VARCHAR(45) NULL,
  `defense` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`troops_has_Villages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`troops_has_Villages` (
  `troops_id` INT NOT NULL,
  `Villages_id` INT NOT NULL,
  PRIMARY KEY (`troops_id`, `Villages_id`),
  CONSTRAINT `fk_troops_has_Villages_troops`
    FOREIGN KEY (`troops_id`)
    REFERENCES `mydb`.`troops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_troops_has_Villages_Villages1`
    FOREIGN KEY (`Villages_id`)
    REFERENCES `mydb`.`Villages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Villages_has_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Villages_has_resources` (
  `Villages_id` INT NOT NULL,
  `Villages_players_id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  PRIMARY KEY (`Villages_id`, `Villages_players_id`, `resources_id`),
  CONSTRAINT `fk_Villages_has_resources_Villages1`
    FOREIGN KEY (`Villages_id` , `Villages_players_id`)
    REFERENCES `mydb`.`Villages` (`id` , `players_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Villages_has_resources_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`buildings_has_Villages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buildings_has_Villages` (
  `buildings_id` INT NOT NULL,
  `Villages_id` INT NOT NULL,
  `Villages_players_id` INT NOT NULL,
  PRIMARY KEY (`buildings_id`, `Villages_id`, `Villages_players_id`),
  CONSTRAINT `fk_buildings_has_Villages_buildings1`
    FOREIGN KEY (`buildings_id`)
    REFERENCES `mydb`.`buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buildings_has_Villages_Villages1`
    FOREIGN KEY (`Villages_id` , `Villages_players_id`)
    REFERENCES `mydb`.`Villages` (`id` , `players_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
